### ISSUE TITLE
TypeError: ord() expected string of length 1, but int found

### ISSUE THREAD

**Issue by K1l14** [schdub/BGENCD#1]
Python 3.5.0

Traceback (most recent call last):
  File "bgencd.py", line 22, in <module>
    d = BGENCD(fi.read())
  File "bgencd.py", line 14, in BGENCD
    l.append(chr(ord(d[i])^ord(s[sb])))
TypeError: ord() expected string of length 1, but int found

Edit:

l.append(chr(ord(d[i])^ord(s[sb])))

ord(d[i]) is the problem, but removing ord doesn't cut it.
I printed out d[I] and s[sb] and it seems that d[i] is missing chars, they print blank.
I tried a bytearray and they still printed blank..

It seems to decrypt fine, I haven't noticed anything missing, but encrypt seems to be borked...

**Comment by K1l14** [comment]
Fixed this, will add it later. Got it to overwrite the file, just got to fix the white space issue.

**Comment by K1l14** [comment]
Fix applied, but I was wondering about this:

sys.stdout.write('BGENCD>>')
sys.stdout.write(d)

This could be removed? Since I'm writing back to the file, there would be no need for the print out?
